<a href="https://colab.research.google.com/github/priyanka-kris/Dlithe-Internship---Python-and-Datascience/blob/main/DAY%2010/_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Day 10**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr = np.random.randint(0, 10, (5, 3))
arr

array([[2, 8, 7],
       [7, 0, 1],
       [6, 1, 1],
       [6, 2, 5],
       [8, 7, 8]])

In [ ]:
df = pd.DataFrame(arr)
df

0  1  2
0  2  8  7
1  7  0  1
2  6  1  1
3  6  2  5
4  8  7  8

In [ ]:
df.values

array([[2, 8, 7],
       [7, 0, 1],
       [6, 1, 1],
       [6, 2, 5],
       [8, 7, 8]])

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
for c in df.columns:
  print(c)

0
1
2


In [ ]:
df.values[1]

array([7, 0, 1])

In [ ]:
df.index = ["R1", "R2", "R3", "R4", "R5"]
df.columns = ["C1", "C2", "C3"]

In [ ]:
df

C1  C2  C3
R1   2   8   7
R2   7   0   1
R3   6   1   1
R4   6   2   5
R5   8   7   8

In [ ]:
df.loc["R3", "C2"]

1

In [ ]:
df.iloc[2, 1]

1

In [ ]:
temp_df = df.iloc[2:4, 1:3]

In [ ]:
temp_df

C2  C3
R3   1   1
R4   2   5

In [ ]:
type(temp_df)

pandas.core.frame.DataFrame

In [ ]:
df.iloc[0]

C1    2
C2    8
C3    7
Name: R1, dtype: int64

In [ ]:
type(df.iloc[0])

pandas.core.series.Series

In [ ]:
df.iloc[:, 0]

R1    2
R2    7
R3    6
R4    6
R5    8
Name: C1, dtype: int64