<a href="https://colab.research.google.com/github/priyanka-kris/Dlithe-Internship---Python-and-Datascience/blob/main/DAY%209/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Day 9**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# series, Dataframe

In [ ]:
s = pd.Series([0,1,1,2,3,5,8])

In [ ]:
s

0    0
1    1
2    1
3    2
4    3
5    5
6    8
dtype: int64

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
s = pd.Series([0.0,1,1,2,3,5,8])

In [ ]:
s

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    5.0
6    8.0
dtype: float64

In [ ]:
s.values

array([0., 1., 1., 2., 3., 5., 8.])

In [ ]:
type(s.values)

numpy.ndarray

In [ ]:
s.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
for v in s.values:
  print(v)

0.0
1.0
1.0
2.0
3.0
5.0
8.0


In [ ]:
for i in s.index:
  print(i)

0
1
2
3
4
5
6


In [ ]:
for item in zip(s.index, s.values):
  print(item, type(item))

(0, 0.0) <class 'tuple'>
(1, 1.0) <class 'tuple'>
(2, 1.0) <class 'tuple'>
(3, 2.0) <class 'tuple'>
(4, 3.0) <class 'tuple'>
(5, 5.0) <class 'tuple'>
(6, 8.0) <class 'tuple'>


In [ ]:
s[5]

5.0

In [ ]:
s[0]

0.0

In [ ]:
pd.Series([0.33, 57.9, 4222.6])

0       0.33
1      57.90
2    4222.60
dtype: float64

In [ ]:
# mass, diameter, dayLength
mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [ ]:
mercury

Mass            0.33
Diameter       57.90
DayLength    4222.60
dtype: float64

In [ ]:
mercury["Mass"]

0.33

In [ ]:
mercury["DayLength"]

4222.6

In [ ]:
arr = np.random.randint(0, 10, 10)
arr

array([8, 0, 5, 7, 2, 1, 5, 0, 7, 2])

In [ ]:
rand_series = pd.Series(arr)
rand_series

0    8
1    0
2    5
3    7
4    2
5    1
6    5
7    0
8    7
9    2
dtype: int64

# iLoc and Loc

In [ ]:

mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [ ]:
mercury["Mass"]

0.33

In [ ]:
mercury[0]

0.33

In [ ]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=[1, 2, 3])

In [ ]:
mercury[0]

KeyError: ignored

In [ ]:
mercury[1]

0.33

In [ ]:
mercury.loc[1]

0.33

In [ ]:
mercury.iloc[1]

57.9

In [ ]:
#  0 1 2 3 4 5   -> implicit indexing(iLoc)
#  2 3 4 5 6 7   -> explicit indexing(Loc)
# [1 2 3 4 5 6]

In [ ]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [ ]:
mercury.loc["Mass":"Diameter"]

Mass         0.33
Diameter    57.90
dtype: float64

In [ ]:
mercury.loc["Mass":]

Mass            0.33
Diameter       57.90
DayLength    4222.60
dtype: float64

In [ ]:
mercury.loc[:]

Mass            0.33
Diameter       57.90
DayLength    4222.60
dtype: float64

In [ ]:
mercury.loc[::-1]

DayLength    4222.60
Diameter       57.90
Mass            0.33
dtype: float64

In [ ]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=[1, 2, 3])

In [ ]:
mercury.loc[1:2]

1     0.33
2    57.90
dtype: float64

In [ ]:
mercury.iloc["Mass"]

TypeError: ignored

In [ ]:
mercury.iloc

In [ ]:
mercury.iloc[]

SyntaxError: ignored

In [ ]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [ ]:
mercury.iloc[0]

0.33

In [ ]:
mercury.iloc[2]

4222.6

In [ ]:
mercury.loc["Mass"]

0.33

In [ ]:
mercury.loc["DayLength"]

4222.6

# Nifty Case Study

In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
nifty = pd.read_csv('nifty.csv', index_col=0).iloc[:, 0]

In [ ]:
nifty_df = pd.read_csv('nifty.csv')
type(nifty_df)

pandas.core.frame.DataFrame

In [ ]:
nifty

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
                 ...   
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, Length: 245, dtype: float64

In [ ]:
nifty.head()

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
Name: Close, dtype: float64

In [ ]:
nifty.head(10)

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
08-Jan-2019    10802.15
09-Jan-2019    10855.15
10-Jan-2019    10821.60
11-Jan-2019    10794.95
14-Jan-2019    10737.60
Name: Close, dtype: float64

In [ ]:
nifty.tail()

Date
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, dtype: float64

In [ ]:
nifty.tail(10)

Date
17-Dec-2019    12165.00
18-Dec-2019    12221.65
19-Dec-2019    12259.70
20-Dec-2019    12271.80
23-Dec-2019    12262.75
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, dtype: float64

In [ ]:
np.mean(nifty)

11432.632244897959

In [ ]:
type(nifty)

pandas.core.series.Series

In [ ]:
np.median(nifty)

11512.4

### Question: How many days did the markets close higher than the previous day's close.

In [ ]:
nifty[0]

10910.1

In [ ]:
nifty[1]

10792.5

In [ ]:
nifty[1] - nifty[0]

-117.60000000000036

In [ ]:
nifty[1:]

Date
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
08-Jan-2019    10802.15
                 ...   
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, Length: 244, dtype: float64

In [ ]:
nifty[:-1]

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
                 ...   
23-Dec-2019    12262.75
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
Name: Close, Length: 244, dtype: float64

In [ ]:
nifty[1:] - nifty[:-1]

Date
01-Apr-2019    0.0
01-Aug-2019    0.0
01-Feb-2019    0.0
01-Jan-2019    NaN
01-Jul-2019    0.0
              ... 
31-Dec-2019    NaN
31-Jan-2019    0.0
31-Jul-2019    0.0
31-May-2019    0.0
31-Oct-2019    0.0
Name: Close, Length: 245, dtype: float64

In [ ]:
nifty.values[1:] - nifty.values[:-1]

array([-1.1760e+02, -1.2025e+02,  5.5100e+01,  4.4450e+01,  3.0350e+01,
        5.3000e+01, -3.3550e+01, -2.6650e+01, -5.7350e+01,  1.4920e+02,
        3.5000e+00,  1.4900e+01,  1.7500e+00,  5.4900e+01, -3.9100e+01,
       -9.1250e+01,  1.8300e+01, -6.9250e+01, -1.1900e+02, -9.3500e+00,
       -4.0000e-01,  1.7915e+02,  6.2700e+01,  1.8600e+01,  2.2100e+01,
        1.2810e+02,  6.9500e+00, -1.2580e+02, -5.4800e+01, -5.7400e+01,
       -3.7750e+01, -4.7600e+01, -2.1650e+01, -8.3450e+01, -3.6600e+01,
        1.3110e+02,  5.4400e+01,  1.8000e+00,  8.8450e+01, -4.4800e+01,
       -2.8650e+01, -1.4150e+01,  7.1000e+01,  1.2395e+02,  6.5550e+01,
        5.2000e+00, -2.2800e+01,  1.3265e+02,  1.3315e+02,  4.0500e+01,
        1.5500e+00,  8.3600e+01,  3.5350e+01,  7.0200e+01, -1.1350e+01,
       -6.4150e+01, -1.0265e+02,  1.2900e+02, -3.8200e+01,  1.2495e+02,
        5.3900e+01,  4.5250e+01,  4.4050e+01, -6.9250e+01, -4.5950e+01,
        6.7950e+01, -6.1450e+01,  6.7450e+01, -8.7650e+01,  1.24

In [ ]:
(nifty.values[1:] - nifty.values[:-1]) > 0

array([False, False,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True, False,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
        True,  True, False, False,  True,  True,  True,  True, False,
       False, False,

In [ ]:
np.sum((nifty.values[1:] - nifty.values[:-1]) > 0)

129